/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppPromotionRouteImport } from './routes/app.promotion'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppNoticesRouteImport } from './routes/app.notices'
import { Route as AppMarksRouteImport } from './routes/app.marks'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHrmRouteImport } from './routes/app.hrm'
import { Route as AppHostelRouteImport } from './routes/app.hostel'
import { Route as AppGradesRouteImport } from './routes/app.grades'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppAcademicYearsRouteImport } from './routes/app.academic-years'
import { Route as MarksheetExamIdStudentIdRouteImport } from './routes/marksheet.$examId.$studentId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionRoute = AppPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppMarksRoute = AppMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmRoute = AppHrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => AppRoute,
} as any)
const AppHostelRoute = AppHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicYearsRoute = AppAcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => AppRoute,
} as any)
const MarksheetExamIdStudentIdRoute =
  MarksheetExamIdStudentIdRouteImport.update({
    id: '/marksheet/$examId/$studentId',
    path: '/marksheet/$examId/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic-years': typeof AppAcademicYearsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/grades': typeof AppGradesRoute
  '/app/hostel': typeof AppHostelRoute
  '/app/hrm': typeof AppHrmRoute
  '/app/library': typeof AppLibraryRoute
  '/app/marks': typeof AppMarksRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/promotion': typeof AppPromotionRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
  '/marksheet/$examId/$studentId': typeof MarksheetExamIdStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/academic-years': typeof AppAcademicYearsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/grades': typeof AppGradesRoute
  '/app/hostel': typeof AppHostelRoute
  '/app/hrm': typeof AppHrmRoute
  '/app/library': typeof AppLibraryRoute
  '/app/marks': typeof AppMarksRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/promotion': typeof AppPromotionRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/app': typeof AppIndexRoute
  '/marksheet/$examId/$studentId': typeof MarksheetExamIdStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic-years': typeof AppAcademicYearsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/grades': typeof AppGradesRoute
  '/app/hostel': typeof AppHostelRoute
  '/app/hrm': typeof AppHrmRoute
  '/app/library': typeof AppLibraryRoute
  '/app/marks': typeof AppMarksRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/promotion': typeof AppPromotionRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
  '/marksheet/$examId/$studentId': typeof MarksheetExamIdStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/academic-years'
    | '/app/accounts'
    | '/app/attendance'
    | '/app/calendar'
    | '/app/classes'
    | '/app/exams'
    | '/app/fees'
    | '/app/grades'
    | '/app/hostel'
    | '/app/hrm'
    | '/app/library'
    | '/app/marks'
    | '/app/notices'
    | '/app/payroll'
    | '/app/promotion'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/tenants'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/app/'
    | '/marksheet/$examId/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/academic-years'
    | '/app/accounts'
    | '/app/attendance'
    | '/app/calendar'
    | '/app/classes'
    | '/app/exams'
    | '/app/fees'
    | '/app/grades'
    | '/app/hostel'
    | '/app/hrm'
    | '/app/library'
    | '/app/marks'
    | '/app/notices'
    | '/app/payroll'
    | '/app/promotion'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/tenants'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/app'
    | '/marksheet/$examId/$studentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/academic-years'
    | '/app/accounts'
    | '/app/attendance'
    | '/app/calendar'
    | '/app/classes'
    | '/app/exams'
    | '/app/fees'
    | '/app/grades'
    | '/app/hostel'
    | '/app/hrm'
    | '/app/library'
    | '/app/marks'
    | '/app/notices'
    | '/app/payroll'
    | '/app/promotion'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/tenants'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/app/'
    | '/marksheet/$examId/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  MarksheetExamIdStudentIdRoute: typeof MarksheetExamIdStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promotion': {
      id: '/app/promotion'
      path: '/promotion'
      fullPath: '/app/promotion'
      preLoaderRoute: typeof AppPromotionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notices': {
      id: '/app/notices'
      path: '/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marks': {
      id: '/app/marks'
      path: '/marks'
      fullPath: '/app/marks'
      preLoaderRoute: typeof AppMarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hrm': {
      id: '/app/hrm'
      path: '/hrm'
      fullPath: '/app/hrm'
      preLoaderRoute: typeof AppHrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hostel': {
      id: '/app/hostel'
      path: '/hostel'
      fullPath: '/app/hostel'
      preLoaderRoute: typeof AppHostelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic-years': {
      id: '/app/academic-years'
      path: '/academic-years'
      fullPath: '/app/academic-years'
      preLoaderRoute: typeof AppAcademicYearsRouteImport
      parentRoute: typeof AppRoute
    }
    '/marksheet/$examId/$studentId': {
      id: '/marksheet/$examId/$studentId'
      path: '/marksheet/$examId/$studentId'
      fullPath: '/marksheet/$examId/$studentId'
      preLoaderRoute: typeof MarksheetExamIdStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAcademicYearsRoute: typeof AppAcademicYearsRoute
  AppAccountsRoute: typeof AppAccountsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClassesRoute: typeof AppClassesRoute
  AppExamsRoute: typeof AppExamsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppGradesRoute: typeof AppGradesRoute
  AppHostelRoute: typeof AppHostelRoute
  AppHrmRoute: typeof AppHrmRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMarksRoute: typeof AppMarksRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPromotionRoute: typeof AppPromotionRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicYearsRoute: AppAcademicYearsRoute,
  AppAccountsRoute: AppAccountsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClassesRoute: AppClassesRoute,
  AppExamsRoute: AppExamsRoute,
  AppFeesRoute: AppFeesRoute,
  AppGradesRoute: AppGradesRoute,
  AppHostelRoute: AppHostelRoute,
  AppHrmRoute: AppHrmRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMarksRoute: AppMarksRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPromotionRoute: AppPromotionRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  MarksheetExamIdStudentIdRoute: MarksheetExamIdStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
