/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppGradesRouteImport } from './routes/app.grades'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAcademicYearsRouteImport } from './routes/app.academic-years'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicYearsRoute = AppAcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic-years': typeof AppAcademicYearsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/grades': typeof AppGradesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/academic-years': typeof AppAcademicYearsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/grades': typeof AppGradesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/academic-years': typeof AppAcademicYearsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/classes': typeof AppClassesRoute
  '/app/exams': typeof AppExamsRoute
  '/app/grades': typeof AppGradesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tenants': typeof AppTenantsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/academic-years'
    | '/app/attendance'
    | '/app/classes'
    | '/app/exams'
    | '/app/grades'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/tenants'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/academic-years'
    | '/app/attendance'
    | '/app/classes'
    | '/app/exams'
    | '/app/grades'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/tenants'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/academic-years'
    | '/app/attendance'
    | '/app/classes'
    | '/app/exams'
    | '/app/grades'
    | '/app/roles'
    | '/app/settings'
    | '/app/students'
    | '/app/subjects'
    | '/app/teachers'
    | '/app/tenants'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic-years': {
      id: '/app/academic-years'
      path: '/academic-years'
      fullPath: '/app/academic-years'
      preLoaderRoute: typeof AppAcademicYearsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicYearsRoute: typeof AppAcademicYearsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClassesRoute: typeof AppClassesRoute
  AppExamsRoute: typeof AppExamsRoute
  AppGradesRoute: typeof AppGradesRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicYearsRoute: AppAcademicYearsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppClassesRoute: AppClassesRoute,
  AppExamsRoute: AppExamsRoute,
  AppGradesRoute: AppGradesRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
